project_id = "dgfctwtivkqcfhwqgkya"

[functions.moderate-content]
verify_jwt = true

[functions.family-approval-request]
verify_jwt = true

[functions.send-family-invitation]
verify_jwt = true

[functions.create-google-meet]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-daily-limit]
verify_jwt = true

[functions.log-profile-view]
verify_jwt = true

[functions.send-conversation-ended-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-match-notification]
verify_jwt = false

[functions.send-match-notifications]
verify_jwt = false