import { useState, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

export type WaliActionType =
  | 'match_approval'
  | 'profile_view'
  | 'settings_modification'
  | 'notification_send';

interface RateLimitConfig {
  match_approval: { limit: 20; windowHours: 24 };
  profile_view: { limit: 50; windowHours: 1 };
  settings_modification: { limit: 10; windowHours: 1 };
  notification_send: { limit: 30; windowHours: 24 };
}

const RATE_LIMITS: RateLimitConfig = {
  match_approval: { limit: 20, windowHours: 24 },
  profile_view: { limit: 50, windowHours: 1 },
  settings_modification: { limit: 10, windowHours: 1 },
  notification_send: { limit: 30, windowHours: 24 },
};

export const useWaliRateLimit = () => {
  const { toast } = useToast();
  const [checking, setChecking] = useState(false);

  /**
   * Vérifie si l'utilisateur est sous la limite pour une action donnée
   */
  const checkRateLimit = useCallback(
    async (userId: string, actionType: WaliActionType): Promise<boolean> => {
      try {
        setChecking(true);

        const config = RATE_LIMITS[actionType];

        // @ts-ignore - RPC function types will be regenerated by Supabase
        const { data, error } = await supabase.rpc('check_wali_rate_limit', {
          p_user_id: userId,
          p_action_type: actionType,
          p_limit_per_window: config.limit,
          p_window_hours: config.windowHours,
        });

        if (error) {
          console.error('Error checking rate limit:', error);
          return false;
        }

        return (data as boolean) ?? false;
      } catch (error) {
        console.error('Error in checkRateLimit:', error);
        return false;
      } finally {
        setChecking(false);
      }
    },
    []
  );

  /**
   * Incrémente le compteur pour une action
   */
  const incrementRateLimit = useCallback(
    async (userId: string, actionType: WaliActionType): Promise<void> => {
      try {
        // @ts-ignore - RPC function types will be regenerated by Supabase
        const { error } = await supabase.rpc('increment_wali_rate_limit', {
          p_user_id: userId,
          p_action_type: actionType,
        });

        if (error) {
          console.error('Error incrementing rate limit:', error);
        }
      } catch (error) {
        console.error('Error in incrementRateLimit:', error);
      }
    },
    []
  );

  /**
   * Vérifie la limite et affiche un toast si dépassée
   */
  const checkAndWarn = useCallback(
    async (userId: string, actionType: WaliActionType): Promise<boolean> => {
      const allowed = await checkRateLimit(userId, actionType);

      if (!allowed) {
        const config = RATE_LIMITS[actionType];
        const actionLabels: Record<WaliActionType, string> = {
          match_approval: "d'approbations de matches",
          profile_view: 'de vues de profils',
          settings_modification: 'de modifications de paramètres',
          notification_send: "d'envois de notifications",
        };

        toast({
          title: 'Limite atteinte',
          description: `Vous avez atteint la limite ${actionLabels[actionType]} (${config.limit} par ${config.windowHours}h). Veuillez réessayer plus tard.`,
          variant: 'destructive',
        });
      }

      return allowed;
    },
    [checkRateLimit, toast]
  );

  /**
   * Récupère les statistiques de rate limit pour un utilisateur
   */
  const getRateLimitStats = useCallback(async (userId: string) => {
    try {
      const { data, error } = await (supabase as any)
        .from('wali_rate_limits')
        .select('*')
        .eq('user_id', userId);

      if (error) throw error;

      return data ?? [];
    } catch (error) {
      console.error('Error getting rate limit stats:', error);
      return [];
    }
  }, []);

  return {
    checkRateLimit,
    incrementRateLimit,
    checkAndWarn,
    getRateLimitStats,
    checking,
  };
};
