import { useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';

export type WaliActionType = 
  | 'match_approved' 
  | 'match_rejected' 
  | 'match_needs_discussion' 
  | 'profile_viewed' 
  | 'settings_modified' 
  | 'invitation_sent' 
  | 'permission_changed';

interface LogActionParams {
  waliUserId: string;
  actionType: WaliActionType;
  supervisedUserId?: string;
  actionDetails?: Record<string, any>;
  matchId?: string;
  familyMemberId?: string;
  success?: boolean;
  errorMessage?: string;
}

export const useWaliAudit = () => {
  /**
   * Logs une action de Wali dans la table d'audit
   */
  const logAction = useCallback(async (params: LogActionParams): Promise<string | null> => {
    try {
      // @ts-ignore - RPC function types will be regenerated by Supabase
      const { data, error } = await supabase.rpc('log_wali_action', {
        p_wali_user_id: params.waliUserId,
        p_action_type: params.actionType,
        p_supervised_user_id: params.supervisedUserId || null,
        p_action_details: params.actionDetails || {},
        p_match_id: params.matchId || null,
        p_family_member_id: params.familyMemberId || null,
        p_success: params.success ?? true,
        p_error_message: params.errorMessage || null
      });

      if (error) {
        console.error('Error logging wali action:', error);
        return null;
      }

      return data as string | null;
    } catch (error) {
      console.error('Error in logAction:', error);
      return null;
    }
  }, []);

  /**
   * Récupère les actions d'audit pour un Wali
   */
  const getAuditLog = useCallback(async (
    waliUserId: string,
    limit: number = 50
  ) => {
    try {
      const { data, error } = await (supabase as any)
        .from('wali_action_audit')
        .select('*')
        .eq('wali_user_id', waliUserId)
        .order('created_at', { ascending: false })
        .limit(limit);

      if (error) throw error;
      
      return data ?? [];
    } catch (error) {
      console.error('Error getting audit log:', error);
      return [];
    }
  }, []);

  /**
   * Récupère les statistiques d'actions pour un Wali
   */
  const getActionStatistics = useCallback(async (waliUserId: string) => {
    try {
      const { data, error } = await (supabase as any)
        .from('wali_action_statistics')
        .select('*')
        .eq('wali_user_id', waliUserId);

      if (error) throw error;
      
      return data ?? [];
    } catch (error) {
      console.error('Error getting action statistics:', error);
      return [];
    }
  }, []);

  /**
   * Génère un rapport d'audit complet
   */
  const getAuditReport = useCallback(async (
    waliUserId: string,
    startDate?: Date,
    endDate?: Date
  ) => {
    try {
      // @ts-ignore - RPC function types will be regenerated by Supabase
      const { data, error } = await supabase.rpc('get_wali_audit_report', {
        p_wali_user_id: waliUserId,
        p_start_date: startDate?.toISOString() || new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        p_end_date: endDate?.toISOString() || new Date().toISOString()
      });

      if (error) throw error;
      
      return data ?? [];
    } catch (error) {
      console.error('Error getting audit report:', error);
      return [];
    }
  }, []);

  return {
    logAction,
    getAuditLog,
    getActionStatistics,
    getAuditReport
  };
};
