-- Add comprehensive relationship compatibility questions
-- These questions cover modern relationship dynamics and gender equality

-- Section 1: Economic Autonomy and Financial Independence
INSERT INTO compatibility_questions (question_key, question_text, category, question_type, options, weight) VALUES
('financial_independence_essential', 'Dans une relation, il est essentiel que chaque partenaire conserve son indépendance financière complète.', 'economic_autonomy', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('financial_dependency_concern', 'Je ne pourrais pas être épanouie dans une relation où je dépendrais financièrement de mon partenaire.', 'economic_autonomy', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('separate_bank_accounts', 'Les comptes bancaires doivent rester séparés, même en cas de mariage.', 'economic_autonomy', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2),
('maternity_compensation', 'En cas de grossesse/maternité, mon partenaire devrait compenser financièrement la perte de revenus que je subis.', 'economic_autonomy', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2),
('housewife_emancipation', 'Une femme qui choisit d''être femme au foyer renonce à son émancipation.', 'economic_autonomy', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2),
('partner_stable_income', 'Mon partenaire doit avoir sa propre source de revenus stable.', 'economic_autonomy', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('partner_higher_income_ok', 'Il est acceptable que mon partenaire gagne significativement plus que moi.', 'economic_autonomy', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 1),
('partner_job_search', 'Si mon partenaire perd son emploi, il devrait activement chercher un nouveau travail plutôt que de dépendre de mes revenus.', 'economic_autonomy', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2);

-- Section 2: Sharing Domestic and Family Responsibilities
INSERT INTO compatibility_questions (question_key, question_text, category, question_type, options, weight) VALUES
('household_tasks_50_50', 'Les tâches ménagères (ménage, cuisine, courses) doivent être réparties exactement à 50/50.', 'domestic_responsibilities', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('partner_initiative_tasks', 'Mon partenaire doit prendre l''initiative pour les tâches domestiques sans que j''aie à le lui demander.', 'domestic_responsibilities', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('mental_load_sharing', 'La charge mentale (planification, organisation, anticipation) doit être équitablement partagée.', 'domestic_responsibilities', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('women_naturally_better_organizing', 'Il est normal qu''une femme soit naturellement meilleure pour organiser la vie domestique.', 'domestic_responsibilities', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2),
('parental_leave_sharing', 'En cas d''enfants, mon partenaire doit prendre des congés parentaux au même titre que moi.', 'parental_responsibilities', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('childcare_shared_responsibility', 'Les soins aux enfants (bains, devoirs, rendez-vous médicaux) doivent être une responsabilité partagée.', 'parental_responsibilities', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('father_not_helping', 'Un père qui s''occupe activement de ses enfants ne "aide" pas, il fait son travail de parent.', 'parental_responsibilities', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2);

-- Section 3: Decision Making and Power in Relationships
INSERT INTO compatibility_questions (question_key, question_text, category, question_type, options, weight) VALUES
('joint_financial_decisions', 'Toutes les décisions d''investissement (immobilier, épargne, assurance) doivent être prises conjointement.', 'decision_making', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('higher_earner_more_power', 'Celui qui gagne le plus a plus de poids dans les décisions financières importantes.', 'decision_making', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2),
('personal_budget_autonomy', 'Chaque partenaire doit avoir un budget personnel dont il n''a pas à rendre compte.', 'decision_making', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2),
('career_move_discussion', 'Si l''un de nous obtient une opportunité professionnelle nécessitant un déménagement, nous devons en discuter équitablement.', 'decision_making', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('children_decision_consensus', 'La décision d''avoir des enfants (nombre, timing) doit être parfaitement consensuelle.', 'decision_making', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('no_decisions_without_consultation', 'Mon partenaire ne devrait jamais prendre de décision importante me concernant sans me consulter.', 'decision_making', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3);

-- Section 4: Career vs Family Life
INSERT INTO compatibility_questions (question_key, question_text, category, question_type, options, weight) VALUES
('equal_career_importance', 'Ma carrière est aussi importante que celle de mon partenaire.', 'career_family_balance', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('acceptable_career_sacrifice', 'Il est acceptable que l''un de nous sacrifie des opportunités professionnelles pour la famille, à condition que ce soit équitable.', 'career_family_balance', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2),
('partner_support_career', 'Mon partenaire doit activement soutenir mes ambitions professionnelles (networking, formation, heures supplémentaires).', 'career_family_balance', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('sick_child_alternating', 'En cas d''enfant malade, la responsabilité de rester à la maison doit être alternée équitablement.', 'career_family_balance', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2),
('mother_slow_career', 'Il est normal qu''une mère ralentisse sa carrière pendant les premières années de vie de l''enfant.', 'career_family_balance', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2),
('partner_adapt_schedule', 'Mon partenaire doit être prêt à adapter ses horaires de travail pour les besoins familiaux.', 'career_family_balance', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2);

-- Section 5: Vision of Marriage
INSERT INTO compatibility_questions (question_key, question_text, category, question_type, options, weight) VALUES
('traditional_marriage_roles', 'Les rôles traditionnels de mariage (qui propose, qui paie, qui organise) doivent être remis en question.', 'marriage_vision', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 2);

-- Section 6: Intimacy and Consent
INSERT INTO compatibility_questions (question_key, question_text, category, question_type, options, weight) VALUES
('explicit_consent', 'Le consentement doit être explicite et peut être retiré à tout moment, même dans une relation établie.', 'intimacy_consent', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('partner_harassment_awareness', 'Mon partenaire doit être sensibilisé aux questions de harcèlement et de comportements sexistes.', 'intimacy_consent', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3),
('respect_boundaries', 'Il est essentiel que mon partenaire comprenne et respecte mes limites sans que j''aie à me justifier.', 'intimacy_consent', 'likert_scale', '["1 - Pas du tout d''accord", "2 - Plutôt pas d''accord", "3 - Neutre", "4 - Plutôt d''accord", "5 - Tout à fait d''accord"]', 3);