// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/utils/logger';

// Configuration Supabase - Environment variables required
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js-web',
    },
  },
});

// Handle session expiry gracefully
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    logger.auth.log('Token refreshed successfully');
  }

  if (event === 'SIGNED_OUT') {
    logger.auth.log('User signed out - cleaning up');
    // Clean up any active realtime subscriptions
    supabase.removeAllChannels();
  }

  // Gérer la récupération de mot de passe
  if (event === 'PASSWORD_RECOVERY') {
    logger.auth.log('Password recovery detected - redirecting to reset password page');
    window.location.href = '/reset-password';
  }
});

// Handle realtime connection errors
if (typeof window !== 'undefined') {
  window.addEventListener('online', () => {
    logger.realtime.log('Network online - reconnecting realtime');
    supabase.realtime.connect();
  });

  window.addEventListener('offline', () => {
    logger.realtime.log('Network offline - pausing realtime');
    supabase.realtime.disconnect();
  });
}
